import { Component, inject, signal, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FirestoreService, VideoItem } from '../services/firestore.service';

@Component({
  selector: 'app-studio',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="section">
      <div class="section-head">
        <p class="kicker">/ video studio</p>
        <h2 class="title">AI video studio</h2>
        <p class="sub">
          Long-form videos generated by <strong>stitching descriptive AI images</strong> over AI narration —
          DeepSeek-v4-pro writes the script, xAI Grok paints each scene, macOS-grade TTS narrates, and ffmpeg
          assembles a narrated Ken-Burns film with a transcript + captions. It's more reliable and far cheaper
          at length than direct text-to-video. <a routerLink="/studio-how" class="go">How it works →</a>
        </p>
      </div>

      @if (videos().length === 0) {
        <p class="muted">No videos published yet. Run the pipeline (<code>studio/generate.mjs</code>) and they appear here automatically. <a routerLink="/studio-how">See how it works →</a></p>
      }

      <div class="grid">
        @for (v of videos(); track v.id) {
          <article class="vcard">
            @if (v.videoUrl) {
              <video class="player" controls preload="none" [poster]="v.thumbUrl || ''"><source [src]="v.videoUrl" type="video/mp4"></video>
            } @else if (v.thumbUrl) {
              <img class="player" [src]="v.thumbUrl" alt="">
            }
            <h3>{{ v.title }}</h3>
            <div class="meta small">
              @if (v.durationSec) { <span>{{ (v.durationSec/60) | number:'1.1-1' }} min</span> }
              @if (v.segments) { <span> · {{ v.segments }} scenes</span> }
              @if (v.status === 'local-only') { <span> · rendered locally</span> }
            </div>
            @if (v.description) { <p class="desc">{{ v.description }}</p> }
            @if (v.transcript) { <details><summary>Transcript</summary><pre>{{ v.transcript }}</pre></details> }
          </article>
        }
      </div>
    </div>
  `,
  styles: [`
    .grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(320px,1fr)); gap:1rem; }
    .vcard { border:1px solid var(--line-soft); border-radius:12px; padding:.9rem 1rem; background:var(--surface); }
    .player { width:100%; border-radius:8px; background:#000; aspect-ratio:16/9; object-fit:cover; }
    .vcard h3 { font-family:var(--display); font-size:1.1rem; margin:.6rem 0 .2rem; }
    .meta { color:var(--muted); font-family:var(--mono); }
    .desc { color:var(--ink-2); font-size:.9rem; margin:.4rem 0 0; }
    details summary { cursor:pointer; font-family:var(--mono); font-size:.72rem; color:var(--solar); margin-top:.4rem; }
    details pre { white-space:pre-wrap; font-size:.82rem; background:#0a0a0a; border:1px solid var(--line-soft); border-radius:8px; padding:.6rem; margin:.4rem 0 0; max-height:260px; overflow:auto; }
    .muted { color:var(--muted); }
  `],
})
export class Studio implements OnInit, OnDestroy {
  private fs = inject(FirestoreService);
  videos = signal<VideoItem[]>([]);
  private unsub?: () => void;
  ngOnInit() { this.unsub = this.fs.listenVideos((v) => this.videos.set(v)); }
  ngOnDestroy() { this.unsub?.(); }
}
