// Baked-in seed data — rendered as a fallback when the live Firestore collections
// are still empty (e.g. before the first agentic scan, or before the Blaze plan +
// scheduled functions are enabled). Pages prefer live Firestore data and fall back
// to this so the site is never empty. Mirrors the seed.json pattern used across
// Bo's other projects (render seed instantly, upgrade to live when available).
import { Job, PhdProgram, Update } from './services/firestore.service';

export const SEED_JOBS: Job[] = [
  { id: 'seed-anthropic-ml', title: 'ML Engineer, Alignment', company: 'Anthropic', location: 'San Francisco, CA (Remote OK)', url: 'https://www.anthropic.com/careers', visaSponsorship: 'sponsorship varies by role', description: 'Scalable oversight and interpretability for frontier models; strong research/engineering track record.', level: 'Staff', source: 'seed' },
  { id: 'seed-openai-redteam', title: 'Red Team Engineer', company: 'OpenAI', location: 'San Francisco, CA', url: 'https://openai.com/careers', visaSponsorship: 'visa sponsorship available', description: 'Adversarial testing of frontier models, jailbreak research, and safety evaluations.', level: 'Senior', source: 'seed' },
  { id: 'seed-xai-infra', title: 'AI Engineer, Infrastructure', company: 'xAI', location: 'Bay Area, CA', url: 'https://x.ai/careers', visaSponsorship: 'international candidates welcome', description: 'Training and inference infrastructure for Grok; deep systems + ML experience.', level: 'Staff', source: 'seed' },
  { id: 'seed-deepseek-research', title: 'Research Engineer (international / visa track)', company: 'DeepSeek', location: 'Hangzhou / Beijing (relocation supported)', url: 'https://www.deepseek.com/', visaSponsorship: 'visa sponsorship + relocation for strong candidates', description: 'Long-context reasoning, agentic systems, and post-training behind the DeepSeek V-series. International applicants encouraged.', level: 'Senior / Staff', source: 'seed' },
  { id: 'seed-deepmind-safety', title: 'Research Scientist, AI Safety', company: 'Google DeepMind', location: 'London / Mountain View', url: 'https://deepmind.google/about/careers/', visaSponsorship: 'visa sponsorship available', description: 'Scalable alignment, robustness, and societal impact of frontier models.', level: 'Research Scientist', source: 'seed' },
  { id: 'seed-anthropic-evals', title: 'Software Engineer, Evaluation Infrastructure', company: 'Anthropic', location: 'Remote (US)', url: 'https://www.anthropic.com/careers', visaSponsorship: 'sponsorship varies by role', description: 'Eval harnesses, data pipelines, and tooling for model assessment at scale.', level: 'Mid–Senior', source: 'seed' },
  { id: 'seed-meta-fair', title: 'Research Engineer, FAIR', company: 'Meta', location: 'Menlo Park / NYC', url: 'https://www.metacareers.com/', visaSponsorship: 'sponsorship available', description: 'Open research and open-weight models (Llama), vision, and ML systems.', level: 'Senior', source: 'seed' },
  { id: 'seed-redteam-generic', title: 'LLM Red Team / Adversarial ML Engineer', company: 'AI safety & security teams (various)', location: 'Remote / US / EU', url: 'https://erosolar.org/jobs', visaSponsorship: 'varies', description: 'Adversarial testing, jailbreak research, evals, and AI security across frontier labs and strong AI teams.', level: 'Mid–Senior', source: 'seed' },
];

export const SEED_PHDS: PhdProgram[] = [
  { id: 'seed-stanford', program: 'Stanford CS PhD (AI/ML)', uni: 'Stanford', country: 'US', status: 'open', deadline: 'early Dec 2026', notes: 'Foundation models + agents; apply to the dept, match an advisor year 1.', visaNotes: 'Standard F-1; strong international support.', lastChecked: '2026-06-14' },
  { id: 'seed-mit', program: 'MIT EECS PhD (AI)', uni: 'MIT', country: 'US', status: 'open', deadline: 'mid-Dec 2026', notes: 'CSAIL + Schwarzman College of Computing; admitted to the department.', visaNotes: 'Excellent support for international admits.', lastChecked: '2026-06-14' },
  { id: 'seed-cmu', program: 'CMU SCS PhD (LTI / MLD / RI)', uni: 'CMU', country: 'US', status: 'open', deadline: 'Dec 2026', notes: 'Apply to the specific institute; legendary for language, ML, robotics.', visaNotes: 'Very international-friendly.', lastChecked: '2026-06-14' },
  { id: 'seed-tsinghua', program: 'Tsinghua CS / AI PhD (IIIS)', uni: 'Tsinghua', country: 'CN', status: 'rolling', deadline: 'varies by lab (often Mar–May)', notes: 'Top Chinese AI program; growing international cohort.', visaNotes: 'CSC scholarships + university support.', lastChecked: '2026-06-14' },
  { id: 'seed-hkust', program: 'HKUST CSE PhD (AI)', uni: 'HKUST', country: 'HK', status: 'open', deadline: 'Dec 2026 / Jan 2027 round', notes: 'Hong Kong PhD Fellowship eligible; strong for ML systems + agents.', visaNotes: 'Attractive HK post-study work visa.', lastChecked: '2026-06-14' },
  { id: 'seed-mila', program: 'Mila PhD (UdeM / McGill)', uni: 'Mila', country: 'CA', status: 'open', deadline: 'Dec 2026', notes: 'Apply to the host university, indicate Mila advisors; deep-learning hub.', visaNotes: 'Friendlier Canadian immigration pathways.', lastChecked: '2026-06-14' },
];

export const SEED_UPDATES: Update[] = [
  { date: '2026-06-14', type: 'site', title: 'Day 1 — erosolar.org becomes the central agentic portfolio + career platform', body: 'Rebuilt erosolar.org into one home for the résumé, the mental-health statements, the full project body of work (Anvilwing, Frontier Model Index, erosolar, The Meridian, DRIFT, Trenchwork, Endearo), a comprehensive PhD & AI-labs directory across every region, a daily AI-jobs board, and admin-controlled agentic outreach + auto-apply. Backend wires DeepSeek-v4-pro + Tavily; everything dated, logged, and owner-controlled.', agent: 'launch' },
  { date: '2026-06-14', type: 'phd', title: 'PhD & AI-labs directory: ~70 programs and labs, every region, sortable by location', body: 'Published an expandable directory covering the US in depth (MIT, Stanford, Harvard, CMU, Berkeley and ~20 more), China, Hong Kong, Canada, the UK, the rest of Europe, Israel & the Middle East, the rest of Asia, and Australia — plus industry labs (Anthropic, OpenAI, Google DeepMind, Meta FAIR, MSR, AI2, DeepSeek, Qwen). Live application status is tracked agentically.', agent: 'deepseek-v4-pro + tavily' },
  { date: '2026-06-13', type: 'jobs', title: 'Daily AI-jobs scan wired (AI labs + AI-eng / red-team / AI-dev)', body: 'Stood up the agentic daily job scan across Anthropic, OpenAI, xAI, Google DeepMind, DeepSeek, Meta and beyond, plus non-lab AI-engineering, red-team, and AI-development roles. Visa/sponsorship is flagged per posting (DeepSeek and similar note visa processes for international applicants).', agent: 'deepseek-v4-pro + tavily' },
  { date: '2026-06-12', type: 'outreach', title: 'Outreach + auto-apply engine: admin-gated, logged, off by default', body: 'Added the Google-SSO admin portal, the DeepSeek + Tavily co-pilot chatbot, and the outreach / auto-apply toggles (default OFF). When enabled, the local Proton-Bridge worker drafts personalized, honest applications from the shipped-project résumé and logs the complete text + status to a full, auditable history.', agent: 'admin' },
];
